### ISSUE TITLE
PaleMoon support

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/FFCK#2]
@ by Roman-Nopantski
Just wanted to add to your palemoon section at the start to save you the work, since that little section came from the ghacks user.js anyway - just append

``` bash
// 3204: (v25.6+) Controls whether to completely ignore "autocomplete=off" on login fields
// user_pref("signon.ignoreAutocomplete", false);
// 3205: (v26.0+) read Moonchild's description on the palemoon forum thread linked above
// user_pref("dom.disable_beforeunload", true);
```

Cheers.

**Comment by CHEF-KOCH** [comment]
Hey, you can create pull request, they are always welcome. :)

I consider to remove the PaleMoon section because I can't test, if it's okay?

**Comment by Roman-Nopantski** [comment]
I no longer run a PM myself, so let's leave it open until someone can confirm, although the information is from moonchild direct. Having said that, maybe we should strip all PM stuff since PM and FF are too widely divergent as far as I'm concerned.
