### ISSUE TITLE
user.js android is incomplete

### ISSUE THREAD

**Issue by gallegonovato** [CHEF-KOCH/FFCK#23]
Good afternoon to you:

First of all thank him for his work. He does more than explendido work.

I wanted to ask you about your user for fennec. Being looking at web like:

https://victorhck.gitlab.io/privacytools-es/#about_config or as https://theprivacyguide1.github.io/about_config.html or https:///gist.github.com/0XDE57/fbd302cef76e62c769#privacy with some differences in their user settings. I don’t know if I could fix them?. 

A hug

**Comment by CHEF-KOCH** [comment]
* Why not link the original privacytoolsio page?
* theprivacyguide1.github.io is outdated
* The third link does not work for me even with correct prefix.

I see nothing missing here. Some suggestions and mentions under Android will 1) not work 2) will break Fennec or 3) result in problems.

Merry Christmas.

**Comment by gallegonovato** [comment]
toolkit.datacollection.infoURL " "
svg.disabled false
svg.display-lists.hit-testing.enabled true
svg.display-lists.painting.enabled true
svg.new-getBBox.enabled true
svg.transform-box.enabled true
geo.wifi.uri
privacy.trackingprotection.enabled true no false 
privacy.resistFingerprintings true no false

And more tan:


https://victorhck.gitlab.io/privacytools-es/#about_config

https://gist.github.com/0XDE57/fbd302cef7693e62c769#privacy-settings

A hug

**Comment by CHEF-KOCH** [comment]
They do not work on Android and are not needed. As said Android Firefox based versions (Fennec) is already privacy focused.

**Comment by gallegonovato** [comment]
In this page:

https://victorhck.gitlab.io/privacytools-es/#about_config lack:

privacy.resistFingerprinting = true
privacy.trackingprotection.enabled = true
privacy.trackingprotection.enabled = true
browser.sessionstore.max_tabs_undo = 0
browser.urlbar.speculativeConnect.enabled = false
media.gmp-widevinecdm.enabled = false
extensions.blocklist.url = https://blocklists.settings.services.mozilla.com/v1/blocklist/3/%20/%20/
extensions.blocklist.enabled = false


toolkit.datacollection.infoURL " "
svg.disabled false
svg.display-lists.hit-testing.enabled true
svg.display-lists.painting.enabled true
svg.new-getBBox.enabled true
svg.transform-box.enabled true
geo.wifi.uri
privacy.trackingprotection.enabled true no false
privacy.resistFingerprintings true no false

And https://gist.github.com/0XDE57/fbd302cef7693e62c769#privacy-settings

plugins.enumerable_names = en blanco
network.http.sendRefererHeader = 0
network.http.sendSecureXSiteReferrer = false
privacy.trackingprotection.enabled = true
geo.wifi.uri = en blanco
browser.safebrowsing.enabled = false
browser.selfsupport.url = en blanco
browser.aboutHomeSnippets.updateUrL = en blanco
browser.startup.homepage_override.mstone = ignore
browser.startup.homepage_override.buildID = en blanco
startup.homepage_welcome_url = en blanco
startup.homepage_welcome_url.additional = en blanco
startup.homepage_override_url = en blanco
toolkit.telemetry.cachedClientID = en blanco
network.cookie.cookieBehavior
        Disable cookies.
        0 = All cookies are allowed. (Default) 
        1 = Only cookies from the originating server are allowed. (block third party cookies)
        2 = No cookies are allowed. 
	3 = Third-party cookies are allowed only if that site has stored cookies already from a previous visit
network.cookie.lifetimePolicy 
        cookies are deleted at the end of the session
        0 = The cookie's lifetime is supplied by the server. (Default) 
        1 = The user is prompted for the cookie's lifetime. 
        2 = The cookie expires at the end of the session (when the browser closes). 
        3 = The cookie lasts for the number of days specified by network.cookie.lifetime.days.
network.dnsCacheEntries = 100
network.dnsCacheExpiration = 60
places.history.enabled = false
network.websocket.enabled = false
loop.enabled = false
extensions.pocket.site = en blanco
extensions.pocket.oAuthConsumerKey = en blanco
extensions.pocket.api = en blanco
privacy.resistFingerprinting = true
privacy.firstparty.isolate = true

Privacy :

set to empty :
toolkit.telemetry.server 
set to false:
browser.newtabpage.activity-stream.feeds.telemetry
browser.newtabpage.activity-stream.telemetry
browser.ping-centre.telemetry
toolkit.telemetry.archive.enabled
toolkit.telemetry.bhrPing.enabled
toolkit.telemetry.enabled
toolkit.telemetry.firstShutdownPing.enabled
toolkit.telemetry.hybridContent.enabled
toolkit.telemetry.newProfilePing.enabled
toolkit.telemetry.reportingpolicy.firstRun
toolkit.telemetry.shutdownPingSender.enabled
toolkit.telemetry.unified
toolkit.telemetry.updatePing.enabled
experiments.activeExperiment
experiments.enabled
experiments.supported
network.allow-expériences

A hug AND MERRY CHRISMAST

**Comment by CHEF-KOCH** [comment]
* Some of those mentioned flags are blindly copied and do not exist on Android or are not working.
* More is not better.
* Some flags draining too much battery or are introducing no real benefit (beta flags like toruplift).
