### ISSUE TITLE
/Anti-Corp/hosts/Qualcomm.txt dont update adaway

### ISSUE THREAD

**Issue by gallegonovato** [CHEF-KOCH/FFCK#24]
Good afternoon:

 I get in touch with you to see if I could update CHEF-KOCH's Qualcomm HOSTS Filter List from the link https://gitlab.com/CHEF-KOCH/cks-filterlist/raw/master/Anti-Corp/hosts/Qualcomm.txt. For this year 2109 or 2020. So Adaway does not trouble. If I were so kind to do it, I would be very grateful to you.

 A hug

**Comment by CHEF-KOCH** [comment]
Wrong repository.
