### ISSUE TITLE
How to download and install user-android.js

### ISSUE THREAD

**Issue by gallegonovato** [CHEF-KOCH/FFCK#25]
I don't know if you could tell me the URL to download your Android user.js . That is https: //github.com/CHEF-KOCH/FFCK/blob/master/user.js/user-android.js ?

Thanks for your help

**Comment by gallegonovato** [comment]
I can not donloads this user. Can you help me?

**Comment by CHEF-KOCH** [comment]
* Download the entire repository.
* Copy the raw file: [https://raw.githubusercontent.com/CHEF-KOCH/FFCK/master/user.js/user-android.js](https://raw.githubusercontent.com/CHEF-KOCH/FFCK/master/user.js/user-android.js) (_and right-click "Save as"_)
* VIa [GitHub Mate](https://github.com/camsong/chrome-github-mate) or [Enhanced Github](https://chrome.google.com/webstore/detail/enhanced-github/anlikcnbgdeidpacdbdljnabclhahhmd/related) or [GitZIp](https://chrome.google.com/webstore/detail/gitzip-for-github/ffabmkklhbepgcgfonabamgnfafbdlkn) for Firefox users there is [cliget](https://addons.mozilla.org/en-US/firefox/addon/cliget/)
* Via curl `curl -OL https://raw.githubusercontent.com/<username>/<repo-name>/<branch-name>/path/to/file` (O downloads the content and L follows the redirection).

**Comment by gallegonovato** [comment]
Please i could download that user?.
