### ISSUE TITLE
Doubt with mozilla.cfg and user.js

### ISSUE THREAD

**Issue by gallegonovato** [CHEF-KOCH/FFCK#27]
Good afternoon:

First of all I wish you a HAPPY NEW YEAR.

Then apologize if I ask a question that is obvious to other people. But not to me, and I don't know how to do it.

It turns out that I wanted to put the user.js for mozilla. But I don't know how to put it.

I see a file called mozilla.cfg. This one also goes?. If so, could you tell me how?.

I'm sorry for my clumsiness and my lack of skill in these matters. But I have never done these things. And looking at all your great work has made me itchy for privacy.

I don't know if you'd be so kind as to help me with this.

Thank you so much for your help.

**Comment by CHEF-KOCH** [comment]
[Customizing Firefox Using AutoConfig](https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig)

**Comment by gallegonovato** [comment]
Good night:

Forgive my ignorance.

Then I have to create a file called asautoconfig.js and in the put:

pref("general.config.filename", "firefox.cfg")
pref("general.config.obscure_value", 0);
pref("autoadmin.global_config_url", "https://github.com/CHEF-KOCH/FFCK/blob/master/user.js/mozilla.cfg");

And then run the file?.

Sorry for my ignorance but if you could help me a little more.


Or download the file mozilla.cfg and run whatever I downloaded from https://github.com/CHEF-KOCH/FFCK/blob/master/user.js/autoconfig.js

Thanks
