### ISSUE TITLE
I don't know if it would be missing and complements fennec?

### ISSUE THREAD

**Issue by gallegonovato** [CHEF-KOCH/FFCK#32]
**Notice**
- [x] I checked the FAQ.md and Readme.md files first.
- [x] I read and accept the Code-of-Conduct.md. Warning: If you deselect this your issue ticket will be closed and the thread gets locked. 
- [x] I checked via GitHub's issue ticket system for already opened/closed tickets (avoiding duplicates).
- [x] I agree that the ticket gets locked + closed after 1 year (automatically) if there aren't any updates on it.
- [x] I agree that bypassing this issue template or a misleading bug report/title will result in a closed ticket. If I continue, I also agree that I get permanent excluded from this project.
- [x] I agree that no one should be forced to decipher screenshots and I also agree that I'm as specific as possible to solve my reported problem.

**Describe the bug or problem**

**To Reproduce**

**Expected behavior**

Good afternoon: I apologize but covered the question well or it is not the right way to ask you these things. In the user.js of fennec would not be missing: user_pref ("_ config.applied", true); to know if everything is applied correctly ?. 

Since Fennec does not cover all the things it puts in the Android user.js. At least mine. Entering from recovery. For example, Google entries do not change them among others.

And I don't know if you could recommend me any complement or complements for fennec ?. ​​

A hug and sorry for the inconvenience

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: Lineageos 15.1in Huawei Nexus 6p
 - Browser Fennec 
 - Version 68.3.0

**Smartphone (please complete the following information in case it's Fennec "Firefox" related):**
 - Device: Huawei Nexus 6p
 - OS: Lineageos 15.1
 - Browser Fennec
 - Version 68.3.0

**Additional context (optional)**

**Comment by CHEF-KOCH** [comment]
I have a discord channel as well as a Matrix channel, if there are common question like this then join and ask me directly. 

[Debugging Fennec](https://wiki.mozilla.org/Mobile/Fennec/Debugging) is a bit more complicated, `config.applied` does not work anymore since several nightly versions.

> And I don't know if you could recommend me any complement or complements for fennec ?. ​​

If you talk about [addons](https://wiki.mozilla.org/Mobile/Fennec/Android/Development/Addons), then I have to disappoint you, I only use uBO.
