### ISSUE TITLE
Various errors etc in user.js

### ISSUE THREAD

**Issue by Roman-Nopantski** [CHEF-KOCH/FFCK#4]
In your "tor" section (line 600) there are some issues :)

`privacy.resistFingerprinting` is already working in FF47+ and will in future include screen orientation which is incorrectly used to describe the next pref

`browser.download.forbid_open_with` is not about screen orientation at all. Here's what I put in the ghacks user.js v.10 (it's in my **To Investigate** section since it hasn't landed in stable yet)
// 2600's: disable "open with" in download dialog (FF48? resolved but not landed yet)
   // This is very useful to enable when the browser is sandboxed (e.g. via AppArmor)
   // in such a way that it is forbidden to run external applications.
   // https://bugzilla.mozilla.org/show_bug.cgi?id=1281959
   // user_pref("browser.download.forbid_open_with", true);

Also, can I suggest you change the section title to something like "Tor Uplift" and include the url ( https://wiki.mozilla.org/Security/Tor_Uplift/Tracking ). It's going to get a lot more items and using a version number (>50) seems odd.

**Comment by Roman-Nopantski** [comment]
Just noticed as well that the e10s section (line 594) holds no e10s prefs. Instead it has `browser.ctrlTab.previews` with an erroneous comment about APZ

Here is what I have for e10s:
// 2650: start the browser in e10s mode (48+)
   // After restarting the browser, you can check whether it's enabled by visiting
   // about:support and checking that "Multiprocess Windows" = 1
   // use force-enable and extensions.e10sblocksenabling if you have add-ons
   // user_pref("browser.tabs.remote.autostart", true);
   // user_pref("browser.tabs.remote.force-enable", true); // (hidden pref)
   // user_pref("extensions.e10sBlocksEnabling", false);

**Comment by Roman-Nopantski** [comment]
line 345, `dom.popup_allowed_events` is a string, you will need to add quotes around the variable

**Comment by CHEF-KOCH** [comment]
Thanks, let me know if something is unclear or wrong. Currently I not really have much time.
